import { makeStyles } from '@mui/styles';

export const usePortfolioStyles = makeStyles((theme) => ({
  // portfolioBox: {
  //   display: 'flex',
  //   flexDirection: 'column',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   maxWidth: '100vw',
  //   width: '100%',
  //   height: '100%',
  //   margin: theme.spacing(0, 'auto'),
  //   padding: theme.spacing(1, 2, 3),
  //   backgroundColor: theme.palette.background.paper,
  //   color: theme.palette.text.primary,
  // },

  paper: {
    background: theme.palette.backgroundD.darkest,
    color: theme.palette.text.primary,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    margin: 'auto',
    width: '100%',
    padding: {
      xs: theme.spacing(1),
      sm: theme.spacing(1),
      md: theme.spacing(2),
      lg: theme.spacing(2),
    },
    borderRadius: theme.shape.borderRadius,
  },
  // paper: {
  //   background: theme.palette.background.main,
  //   color: theme.palette.text.primary,
  //   display: 'flex',
  //   justifyContent: 'center',
  //   flexDirection: 'column',
  //   margin: 'auto',
  //   width: '100%',
  //   padding: theme.spacing(1, 2),
  //   borderRadius: theme.shape.borderRadius,
  // },
  // portfolioBox: {
  //   display: 'flex',
  //   flexDirection: 'column',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   maxWidth: '100vw',
  //   width: '100%',
  //   height: '100%',
  //   margin: { xs: 0, sm: 'auto', md: 'auto', lg: 'auto' },
  //   padding: { xs: 1, sm: 2, md: 3, lg: 3 },
  //   backgroundColor: theme.palette.background.paper,
  //   color: theme.palette.text.primary,
  // },
  // paper: {
  //   background: theme.palette.background.main,
  //   color: theme.palette.text.primary,
  //   display: 'flex',
  //   justifyContent: 'center',
  //   flexDirection: 'column',
  //   margin: 'auto',
  //   width: '100%',
  //   padding: { xs: 1, sm: 1, md: 2, lg: 2 },
  //   borderRadius: theme.shape.borderRadius,
  // },
  gridContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: theme.spacing(1),
    // backgroundColor: theme.palette.background.quinternary,
    background: theme.palette.backgroundB.lighter,
  },
  gridItem: {
    display: 'flex',
    justifyContent: 'flex-end',
    background: theme.palette.success.main,
  },
  portfolioBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(4),
    borderRadius: theme.shape.borderRadius,
    flexGrow: 1,
    // background: theme.palette.success.main,
    background: theme.palette.backgroundC.dark,
    padding: theme.spacing(4),
    height: 'auto',
    width: '100%',
    // height: '100%',
    boxShadow: theme.shadows[5],
    [theme.breakpoints.down('sm')]: {
      padding: theme.spacing(2),
    },
  },
  portfolioBoxB: {
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(4),
    borderRadius: theme.shape.borderRadius,
    flexGrow: 1,
    // background: theme.palette.success.main,
    background: theme.palette.backgroundD.dark,
    padding: theme.spacing(4),
    height: 'auto',
    width: '100%',
    // height: '100%',
    boxShadow: theme.shadows[5],
    [theme.breakpoints.down('sm')]: {
      padding: theme.spacing(2),
    },
  },
  typography: {
    fontWeight: 700,
    color: theme.palette.backgroundC.contrastText,
    fontSize: '1.5rem',
    textAlign: 'left',
    paddingLeft: theme.spacing(2),
    [theme.breakpoints.down('sm')]: {
      fontSize: '1.25rem',
    },
  },
  button: {
    margin: theme.spacing(1),
    padding: theme.spacing(1),
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.getContrastText(theme.palette.primary.main),
    transition: 'background-color 0.3s',
    '&:hover': {
      backgroundColor: theme.palette.primary.dark,
      // Elevate button on hover
      boxShadow: theme.shadows[2],
    },
  },
  // gridContainer: {
  //   width: '100%',
  //   alignItems: 'center',
  //   justifyContent: 'space-between',
  //   padding: theme.spacing(1),
  // },
  // Additional styles
  dialogButton: {
    textTransform: 'none', // or other style adjustments for dialog buttons
  },
  listContainer: {
    // marginTop: theme.spacing(2),
    maxHeight: '60vh', // or other appropriate height
    overflowY: 'auto',
    padding: theme.spacing(2),
    // background: theme.palette.backgroundC.lighter,
  },
  dialogContent: {
    padding: theme.spacing(2),
    background: theme.palette.background.paper,
    // height: '100%',
  },
  boxStyle: {
    padding: theme.spacing(2),
    justifyContent: 'center',
    margin: 'auto',
  },
  cardStyle: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    margin: 'auto',
    padding: theme.spacing(2),
    maxWidth: '100%',
    maxHeight: '100%',
  },
  cardContentStyle: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    margin: 'auto',
    padding: theme.spacing(2),
    maxWidth: '100%',
    maxHeight: '100%',
  },
  cardMediaStyle: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    margin: 'auto',
    padding: theme.spacing(2),
    maxWidth: '100%',
    maxHeight: '100%',
  },
  // Add any other styles from CardPortfolio, PortfolioContent, and SelectCollection components
}));

export default usePortfolioStyles;
