import { rgba } from 'polished';

const colorTextForDark = rgba('white', 0.96);
const colorLabel = '#A4A3A6';
const colorText = '#343239';
const defaultColorTheme = {
  id: 'whiteGreen',
  borderRadius: '0.75rem',
  colorBackground: '#f0f0f9',
  colorNavbar: '#fff',
  colorNavbarLabel: colorLabel,
  colorNavbarLink: colorText,
  colorText: colorText,
  colorLabel: colorLabel,
  colorBorder: '#f0f0f9',
  colorPrimary: '#18b984',

  // colorPrimary: '#06D6A0',
  colorPrimaryText: colorTextForDark,
  colorAccent: '#5fe7bb',
  colorAccentText: colorTextForDark,
  colorCardBackground: '#ffffff',
  colorDefaultBackground: '#e3e3e8',
  colorDefaultText: '#73707C',
  colorDisabledBackground: '#d5d5e3',
  colorDisabledText: '#bebed0',
  colorCode: '#100f10',
  colorChartShading: '#696969',
  boxShadowLogo: 'none',
};
const uniqueTheme = {
  ...defaultColorTheme,
  // screenWidthXs: '480px',
  // screenWidthSm: '576px',
  // screenWidthMd: '768px',
  // screenWidthLg: '992px',
  gutterWidth: '0.5rem',
  containerMaxWidthXs: '100%',
  containerMaxWidthSm: '100%',
  containerMaxWidthMd: '100%',
  containerMaxWidthLg: '1080px',
  containerMaxWidthXl: '1200px',
  screenWidthXs: '576px',
  screenWidthSm: '768px',
  screenWidthMd: '992px',
  screenWidthLg: '1200px',
  screenWidthXl: '1920px',
  sidebarWidth: '56px',
  sidebarWidthMd: '220px',
  colorForDark1: rgba('white', 0.96),
  colorForDark2: rgba('white', 0.65),
  colorForDark3: rgba('white', 0.45),
  fontFamily: 'Poppins',
  fontWeightBold: 600,
  fontWeightSemibold: 500,
  fontWeightRegular: 400,
  heightCardMd: '360px',
  heightChartMd: '150px',
  lenSm1: '0.25rem',
  lenSm2: '0.5rem',
  lenSm3: '0.75rem',
  lenMd1: '1rem',
  lenMd2: '1.25rem',
  lenMd3: '1.5rem',
  lenLg1: '2rem',
  lenLg2: '3rem',
  lenLg3: '4rem',
  lenXl1: '5rem',
  lenXl2: '6rem',
  lenXl3: '7rem',
};

export default uniqueTheme;
